use UNIVER;

--1-Task--
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средние оценки]
FROM FACULTY Inner Join GROUPS
	on FACULTY.FACULTY = GROUPS.FACULTY
	Inner Join STUDENT
	on STUDENT.IDGROUP = GROUPS.IDGROUP
	Inner Join PROGRESS
	on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE FACULTY.FACULTY = 'IT'
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT


SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средние оценки]
FROM FACULTY Inner Join GROUPS
	on FACULTY.FACULTY = GROUPS.FACULTY
	Inner Join STUDENT
	on STUDENT.IDGROUP = GROUPS.IDGROUP
	Inner Join PROGRESS
	on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE FACULTY.FACULTY = 'IT'
GROUP BY ROLLUP (FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)

--2-Task--
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средние оценки]
FROM FACULTY Inner Join GROUPS
	on FACULTY.FACULTY = GROUPS.FACULTY
	Inner Join STUDENT
	on STUDENT.IDGROUP = GROUPS.IDGROUP
	Inner Join PROGRESS
	on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
WHERE FACULTY.FACULTY = 'IT'
GROUP BY CUBE (FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)

--3-Task--
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) as [Средние оценки]
FROM FACULTY Inner Join GROUPS
	on FACULTY.FACULTY = GROUPS.FACULTY 
	Inner Join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	Inner Join PROGRESS
	on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'IT'
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
	UNION
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) as [Средние оценки]
FROM FACULTY Inner Join GROUPS
	on FACULTY.FACULTY = GROUPS.FACULTY 
	Inner Join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	Inner Join PROGRESS
	on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'TOV'
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT



SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) as [Средние оценки]
FROM FACULTY Inner Join GROUPS
	on FACULTY.FACULTY = GROUPS.FACULTY 
	Inner Join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	Inner Join PROGRESS
	on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'IT'
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
	UNION ALL
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) as [Средние оценки]
FROM FACULTY Inner Join GROUPS
	on FACULTY.FACULTY = GROUPS.FACULTY 
	Inner Join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	Inner Join PROGRESS
	on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'TOV'
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT

--4-Task--
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) as [Средние оценки]
FROM FACULTY Inner Join GROUPS
	on FACULTY.FACULTY = GROUPS.FACULTY 
	Inner Join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	Inner Join PROGRESS
	on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'IT'
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
	INTERSECT
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) as [Средние оценки]
FROM FACULTY Inner Join GROUPS
	on FACULTY.FACULTY = GROUPS.FACULTY 
	Inner Join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	Inner Join PROGRESS
	on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'TOV'
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT

--5-Task--
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) as [Средние оценки]
FROM FACULTY Inner Join GROUPS
	on FACULTY.FACULTY = GROUPS.FACULTY 
	Inner Join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	Inner Join PROGRESS
	on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'IT'
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
	EXCEPT
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) as [Средние оценки]
FROM FACULTY Inner Join GROUPS
	on FACULTY.FACULTY = GROUPS.FACULTY 
	Inner Join STUDENT
	on GROUPS.IDGROUP = STUDENT.IDGROUP
	Inner Join PROGRESS
	on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE FACULTY.FACULTY = 'TOV'
GROUP BY FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT