USE UNIVER;

SELECT FACULTY.FACULTY as Факультет, PULPIT.PULPIT as Кафедра
	FROM FACULTY, PULPIT
	WHERE FACULTY.FACULTY = PULPIT.FACULTY
	and FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY FROM PROFESSION
				   WHERE (PROFESSION.PROFESSION_NAME LIKE '%tech%') )