use UNIVER;

Select FACULTY.FACULTY as Факультет, PULPIT.PULPIT as Кафедра
	From FACULTY Inner Join PULPIT
		On PULPIT.FACULTY = FACULTY.FACULTY
			Where FACULTY.FACULTY In (Select PROFESSION.FACULTY From PROFESSION
									  Where PROFESSION.PROFESSION_NAME Like '%tech%')