use UNIVER;

Select DISTINCT
FACULTY.FACULTY as Факультет, PULPIT.PULPIT as Кафедра
	From FACULTY Inner Join PULPIT
		On FACULTY.FACULTY = PULPIT.FACULTY
			Inner Join PROFESSION
				On FACULTY.FACULTY = PROFESSION.FACULTY
					 Where (PROFESSION.PROFESSION_NAME Like '%tech%')